# Generated by Django 4.0.2 on 2022-02-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_cpf_alter_cliente_id_usuario'),
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
